spring:
  profiles:
    active: docker
  datasource:
    url: jdbc:mariadb://aniwhere.cxi4m8w8uege.ap-northeast-2.rds.amazonaws.com/aniwhere
    username: patrick
    password: sukmin1793
    driver-class-name: org.mariadb.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 5FqaEpkU2bXFCNMxciFL
            client-secret: GRBHZbR_oP
            redirect-uri: "https://aniwhere.click/login/oauth2/code/naver"
            scope:
              - name
              - email
          kakao:
            redirect-uri: "https://aniwhere.click/login/oauth2/code/kakao"
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
