spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 5FqaEpkU2bXFCNMxciFL
            client-secret: GRBHZbR_oP
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "https://www.aniwhere.click/login/oauth2/code/naver"
            scope:
              - name
              - email
          kakao:
            client-id: 97073f3ae836af338ca159b6be418974
            client-secret: UewXOCIiuAlzSnfcsdUOQXGBtC2ZRoBY
            client-name: Kakao
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: "https://www.aniwhere.click/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
